"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RC_DAT_GUI.py']
DATA_FILES = ['RC.png', 'RC.ico']
OPTIONS = { 'iconfile':'./RC.ico' }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    py_modules={"tk"},
    setup_requires=['py2app'],
)
